//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisGalaxy.GameEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignEnrollment
    {
        public int campaignId { get; set; }
        public long shipId { get; set; }
        public long crewMemberId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual CrewMember CrewMember { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
