//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisGalaxy.GameEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewMember
    {
        public CrewMember()
        {
            this.CampaignEnrollments = new HashSet<CampaignEnrollment>();
            this.Ships = new HashSet<Ship>();
        }
    
        public long id { get; set; }
        public string login_name { get; set; }
        public string email { get; set; }
        public string passwd { get; set; }
        public string timeZone { get; set; }
        public string characterName { get; set; }
    
        public virtual ICollection<CampaignEnrollment> CampaignEnrollments { get; set; }
        public virtual ICollection<Ship> Ships { get; set; }
    }
}
