//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisGalaxy.GameEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnemyShip
    {
        public EnemyShip()
        {
            this.EnemyShipSectorAssignments = new HashSet<EnemyShipSectorAssignment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public short vesselId { get; set; }
        public int cost { get; set; }
    
        public virtual ICollection<EnemyShipSectorAssignment> EnemyShipSectorAssignments { get; set; }
    }
}
