//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisGalaxy.GameEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnemyShipSectorAssignment
    {
        public long SectorId { get; set; }
        public int EnemyShipId { get; set; }
        public long locationX { get; set; }
        public long locationY { get; set; }
        public short fullAmount { get; set; }
        public short maxAmount { get; set; }
        public short fleetNumber { get; set; }
        public int productionWeight { get; set; }
        public short currentAmount { get; set; }
    
        public virtual EnemyShip EnemyShip { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
