//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisGalaxy.GameEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.EnemyShipSectorAssignments = new HashSet<EnemyShipSectorAssignment>();
        }
    
        public long id { get; set; }
        public int campaignId { get; set; }
        public int locationX { get; set; }
        public Nullable<int> locationY { get; set; }
        public string baseMissionFileName { get; set; }
        public bool canTravelNorth { get; set; }
        public bool canTravelNorthEast { get; set; }
        public bool canTravelEast { get; set; }
        public bool canTravelSouthEast { get; set; }
        public bool canTravelSouth { get; set; }
        public bool canTravelSouthWest { get; set; }
        public bool canTravelWest { get; set; }
        public bool canTravelNorthWest { get; set; }
        public byte difficulty { get; set; }
        public int production { get; set; }
        public bool isClaimed { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<EnemyShipSectorAssignment> EnemyShipSectorAssignments { get; set; }
    }
}
