//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisGalaxy.GameEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public Ship()
        {
            this.CampaignEnrollments = new HashSet<CampaignEnrollment>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public System.DateTime creationDate { get; set; }
        public long ownerId { get; set; }
    
        public virtual ICollection<CampaignEnrollment> CampaignEnrollments { get; set; }
        public virtual CrewMember CrewMember { get; set; }
    }
}
